version: 0.2

phases:
  install:
    commands:
      - yum install java-17-amazon-corretto -y
      - alternatives --set java /usr/lib/jvm/java-17-amazon-corretto/bin/java
  build:
    commands:
      - echo Build started on `date`
      - mvn package
artifacts:
  files:
    - target/AuthorizationService-1.0.jar
    - appspec.yml
    - scripts/start-process.sh
    - scripts/stop-process.sh
    - scripts/install_dependencies.sh
    - scripts/health-check.sh
  discard-paths: yes